Consolidate configurations to recipes. Add 5 second delay for Kong deployment due to slow API server in REC
Signed-off-by: Zhe Huang <zhehuang@research.att.com>
Change-Id: I0f63bd7c4f95760a8a37835fa37ed691641b721b

diff --git a/bin/deploy-ric-platform b/bin/deploy-ric-platform
--- a/bin/deploy-ric-platform
+++ b/bin/deploy-ric-platform
@@ -18,34 +18,38 @@
 
 # This script deploys RIC platform components automatically
 
-OVERRIDEYAML=$1
+while [ -n "$1" ]; do # while loop starts
+
+    case "$1" in
+
+    -f) OVERRIDEYAML=$2
+        shift
+        ;;
+    *) echo "Option $1 not recognized" ;; # In case you typed a different option other than a,b,c
+
+    esac
+
+    shift
+
+done
+
 
 if [ -z "$OVERRIDEYAML" ];then
-echo "****************************************************************************************************************"
-echo "                                                     WARNING                                                    "
-echo "****************************************************************************************************************"
-echo "Deploying RIC platform without deployment recipe. Default configurations are used."
-echo "****************************************************************************************************************"
-
-
+    echo "****************************************************************************************************************"
+    echo "                                                     ERROR                                                      "
+    echo "****************************************************************************************************************"
+    echo "RIC deployment without deployment recipe is currently disabled. Please specify an recipe with the -f option."
+    echo "****************************************************************************************************************"
+    exit 1
 fi
+
 
 
 ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
 
-source $ROOT_DIR/../etc/ric.conf
-
-
-export RICPLT_RELEASE_NAME=$helm_release_name
-
-export RICPLT_NAMESPACE=$plt_namespace
-export RICXAPP_NAMESPACE=$xapp_namespace
-export RICAUX_NAMESPACE=$aux_namespace
-export RICINFRA_NAMESPACE=$infra_namespace
-
 for component in $ROOT_DIR/../ric-platform/*/; do
     # Will print */ if no directories are available
-    . $component/bin/install $OVERRIDEYAML
+    . $component/bin/install -f $OVERRIDEYAML
 
 done
 
