Consolidate configurations to recipes. Add 5 second delay for Kong deployment due to slow API server in REC
Signed-off-by: Zhe Huang <zhehuang@research.att.com>
Change-Id: I0f63bd7c4f95760a8a37835fa37ed691641b721b

diff --git a/bin/deploy-ric-aux b/bin/deploy-ric-aux
--- a/bin/deploy-ric-aux
+++ b/bin/deploy-ric-aux
@@ -18,33 +18,42 @@
 
 # This script deploys RIC aux components automatically
 
-OVERRIDEYAML=$1
+if [ "$#" -eq 1 ]; then
+    OVERRIDEYAML=$1
+else
+
+    while [ -n "$1" ]; do # while loop starts
+
+        case "$1" in
+
+        -f) OVERRIDEYAML=$2
+            shift
+            ;;
+        *) echo "Option $1 not recognized" ;; # In case you typed a different option other than a,b,c
+
+        esac
+
+        shift
+
+    done
+fi
+
 
 if [ -z "$OVERRIDEYAML" ];then
-echo "****************************************************************************************************************"
-echo "                                                     WARNING                                                    "
-echo "****************************************************************************************************************"
-echo "Deploying RIC auxiliary without deployment recipe. Default configurations are used."
-echo "****************************************************************************************************************"
-
+    echo "****************************************************************************************************************"
+    echo "                                                     ERROR                                                      "
+    echo "****************************************************************************************************************"
+    echo "RIC deployment without deployment recipe is currently disabled. Please specify an recipe with the -f option."
+    echo "****************************************************************************************************************"
+    exit 1
 fi
 
 
 ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
 
-source $ROOT_DIR/../etc/ric.conf
-
-
-export RICAUX_RELEASE_NAME=$helm_release_name
-
-export RICPLT_NAMESPACE=$plt_namespace
-export RICXAPP_NAMESPACE=$xapp_namespace
-export RICAUX_NAMESPACE=$aux_namespace
-export RICINFRA_NAMESPACE=$infra_namespace
-
 for component in $ROOT_DIR/../ric-aux/*/; do
     # Will print */ if no directories are available
-    . $component/bin/install $OVERRIDEYAML
+    . $component/bin/install -f $OVERRIDEYAML
 
 done
 
